version: "3.8"

services:
  nginx:
    # image: nginx
    depends_on:
      - wordpress
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - Inception
    volumes:
      - wordpress_volume:/var/www/html
    restart: always

  wordpress:
    # image: wordpress
    depends_on:
      - mariadb
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress_volume:/var/www/html
    env_file:
      - .env
    networks:
      - Inception
    expose:
      - 9000
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    expose:
      - 3306
    env_file: .env
    networks:
      - Inception
    restart: always
    volumes:
      - mariadb_volume:/var/lib/mysql #mariadb is a fork of mysql so theres compatibility

volumes:
  mariadb_volume:
    driver: local
    driver_opts: 
      type: none
      device: /home/teo/data/mariadb
      o: bind 
  wordpress_volume:
    driver: local
    driver_opts: 
      type: none
      device: /home/teo/data/wordpress
      o: bind

networks:
  Inception:
    driver: bridge